// <auto-generated />
using System;
using FaceIdBackend.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FaceIdBackend.Infrastructure.Migrations
{
    [DbContext(typeof(AttendanceSystemContext))]
    partial class AttendanceSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FaceIdBackend.Domain.Data.AttendanceRecord", b =>
                {
                    b.Property<Guid>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AttendanceID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CheckInTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsManualOverride")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SessionID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Present");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StudentID");

                    b.HasKey("AttendanceId")
                        .HasName("PK__Attendan__8B69263CAA59BE09");

                    b.HasIndex(new[] { "CheckInTime" }, "IX_Attendance_CheckInTime");

                    b.HasIndex(new[] { "SessionId" }, "IX_Attendance_SessionID");

                    b.HasIndex(new[] { "Status" }, "IX_Attendance_Status");

                    b.HasIndex(new[] { "StudentId" }, "IX_Attendance_StudentID");

                    b.HasIndex(new[] { "SessionId", "StudentId" }, "UQ_Session_Student")
                        .IsUnique();

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("FaceIdBackend.Domain.Data.AttendanceSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SessionID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClassID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("SessionEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SessionStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("InProgress");

                    b.HasKey("SessionId")
                        .HasName("PK__Attendan__C9F49270DC14CDA5");

                    b.HasIndex(new[] { "ClassId" }, "IX_Sessions_ClassID");

                    b.HasIndex(new[] { "ClassId", "SessionDate" }, "IX_Sessions_Class_Date");

                    b.HasIndex(new[] { "SessionDate" }, "IX_Sessions_Date");

                    b.HasIndex(new[] { "Status" }, "IX_Sessions_Status");

                    b.ToTable("AttendanceSessions");
                });

            modelBuilder.Entity("FaceIdBackend.Domain.Data.Class", b =>
                {
                    b.Property<Guid>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClassID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AzurePersonGroupId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ClassId")
                        .HasName("PK__Classes__CB1927A0A783E26D");

                    b.HasIndex(new[] { "ClassCode" }, "IX_Classes_ClassCode");

                    b.HasIndex(new[] { "IsActive" }, "IX_Classes_IsActive");

                    b.HasIndex(new[] { "ClassCode" }, "UQ__Classes__2ECD4A55E3D4F333")
                        .IsUnique();

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("FaceIdBackend.Domain.Data.ClassEnrollment", b =>
                {
                    b.Property<Guid>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EnrollmentID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClassID");

                    b.Property<DateTime>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StudentID");

                    b.HasKey("EnrollmentId")
                        .HasName("PK__ClassEnr__7F6877FB0FB61386");

                    b.HasIndex(new[] { "ClassId" }, "IX_Enrollments_ClassID");

                    b.HasIndex(new[] { "Status" }, "IX_Enrollments_Status");

                    b.HasIndex(new[] { "StudentId" }, "IX_Enrollments_StudentID");

                    b.HasIndex(new[] { "ClassId", "StudentId" }, "UQ_Class_Student")
                        .IsUnique();

                    b.ToTable("ClassEnrollments");
                });

            modelBuilder.Entity("FaceIdBackend.Domain.Data.SessionSnapshot", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SnapshotID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("AbsentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("AttendanceRate")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("AttendanceRecordsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CapturedImagesFolder")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("GeneratedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LateCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PresentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("RecognitionResultsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("SessionDuration")
                        .HasColumnType("time");

                    b.Property<DateTime?>("SessionEndTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SessionID");

                    b.Property<string>("SessionMetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SessionStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalStudents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("SnapshotId")
                        .HasName("PK__SessionS__SnapshotID");

                    b.HasIndex(new[] { "GeneratedAt" }, "IX_SessionSnapshots_GeneratedAt");

                    b.HasIndex(new[] { "SessionId" }, "IX_SessionSnapshots_SessionID")
                        .IsUnique();

                    b.ToTable("SessionSnapshots");
                });

            modelBuilder.Entity("FaceIdBackend.Domain.Data.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StudentID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AzureFaceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AzurePersonId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId")
                        .HasName("PK__Students__32C52A79FE3CA4F8");

                    b.HasIndex(new[] { "AzurePersonId" }, "IX_Students_AzurePersonId");

                    b.HasIndex(new[] { "IsActive" }, "IX_Students_IsActive");

                    b.HasIndex(new[] { "StudentNumber" }, "IX_Students_StudentNumber");

                    b.HasIndex(new[] { "StudentNumber" }, "UQ__Students__DD81BF6C90048E4A")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("FaceIdBackend.Domain.Data.AttendanceRecord", b =>
                {
                    b.HasOne("FaceIdBackend.Domain.Data.AttendanceSession", "Session")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_Session");

                    b.HasOne("FaceIdBackend.Domain.Data.Student", "Student")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_Student");

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("FaceIdBackend.Domain.Data.AttendanceSession", b =>
                {
                    b.HasOne("FaceIdBackend.Domain.Data.Class", "Class")
                        .WithMany("AttendanceSessions")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Session_Class");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("FaceIdBackend.Domain.Data.ClassEnrollment", b =>
                {
                    b.HasOne("FaceIdBackend.Domain.Data.Class", "Class")
                        .WithMany("ClassEnrollments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Enrollment_Class");

                    b.HasOne("FaceIdBackend.Domain.Data.Student", "Student")
                        .WithMany("ClassEnrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Enrollment_Student");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("FaceIdBackend.Domain.Data.SessionSnapshot", b =>
                {
                    b.HasOne("FaceIdBackend.Domain.Data.AttendanceSession", "Session")
                        .WithOne("SessionSnapshot")
                        .HasForeignKey("FaceIdBackend.Domain.Data.SessionSnapshot", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SessionSnapshot_Session");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("FaceIdBackend.Domain.Data.AttendanceSession", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("SessionSnapshot");
                });

            modelBuilder.Entity("FaceIdBackend.Domain.Data.Class", b =>
                {
                    b.Navigation("AttendanceSessions");

                    b.Navigation("ClassEnrollments");
                });

            modelBuilder.Entity("FaceIdBackend.Domain.Data.Student", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("ClassEnrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
